language: generic
matrix:
  include:
    - env:
        - PKG_CONFIG_DIR=
        - PKG_CONFIG_LIBDIR=/usr/lib/x86_64-linux-gnu/pkgconfig
        - PKG_CONFIG_SYSROOT_DIR=
        - PKG_ALLOW_CROSS=1
        - TARGET=arm-unknown-linux-gnueabi
        - LINKER=arm-linux-gnueabi-gcc
        - PACKAGE=unipager-arm.tar.gz
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabi
            - libc6-armel-cross
            - libc6-dev-armel-cross
            - libudev-dev
    - env:
        - PKG_CONFIG_DIR=
        - PKG_CONFIG_LIBDIR=/usr/lib/x86_64-linux-gnu/pkgconfig
        - PKG_CONFIG_SYSROOT_DIR=
        - PKG_ALLOW_CROSS=1
        - TARGET=arm-unknown-linux-gnueabihf
        - LINKER=arm-linux-gnueabihf-gcc
        - PACKAGE=unipager-rpi2.tar.gz
      addons:
        apt:
          packages: &armhf
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
            - libudev-dev
    - env:
        - PKG_CONFIG_DIR=
        - PKG_CONFIG_LIBDIR=/usr/lib/x86_64-linux-gnu/pkgconfig
        - PKG_CONFIG_SYSROOT_DIR=
        - PKG_ALLOW_CROSS=1
        - TARGET=armv7-unknown-linux-gnueabihf
        - LINKER=arm-linux-gnueabihf-gcc
        - PACKAGE=unipager-rpi3.tar.gz
      addons:
        apt:
          packages: *armhf
            - libudev-dev
    - env:
        - PKG_CONFIG_DIR=
        - PKG_CONFIG_LIBDIR=/usr/lib/x86_64-linux-gnu/pkgconfig
        - PKG_CONFIG_SYSROOT_DIR=
        - PKG_ALLOW_CROSS=1
        - TARGET=i686-unknown-linux-gnu
        - PACKAGE=unipager-i686.tar.gz
      addons:
        apt:
          packages:
            - gcc-multilib
            - libudev-dev
    - env:
        - TARGET=x86_64-unknown-linux-gnu
        - PACKAGE=unipager-x86_64.tar.gz
      addons:
        apt:
          packages:
            - libudev-dev

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=nightly
  - rustup target add $TARGET || true
  - |
    if [ -n "$LINKER" ]; then
      mkdir -p ~/.cargo
      echo >> ~/.cargo/config
      echo "[target.$TARGET]" >> ~/.cargo/config
      echo "linker = \"$LINKER\"" >> ~/.cargo/config
    fi

script:
  - cargo build --target $TARGET --verbose --release

before_deploy:
  - tar -czf $PACKAGE -C target/$TARGET/release/ unipager

deploy:
  provider: releases
  api_key:
    secure: Y0E2keSR4wzpBssjfcUooBF7n6dEdD1HqGs6dFIqO/Z7c3fF97b7cbfXTlO4myZ8zDwSJcQ5uXgojmb7aDhwbY0quPdK69d5zHTC525WqAkOE9hvCbHIJ9bZ+dt7ZmdL7DsNif25c9lTUAu8UyWLZ5LjbSLIaA/oEp2FZ/G01w2gNMPKvlsrN5Rt5R8+ffBDgh5ggBArJIfEdQJnBIMBfS+OmXyr/xAAafAi2dnFUe8x1KyOMMNCgOXGqprxN5tk05HrDyTFzXpzDYGeswg4aSzROdQ8H8T/qnra9CBHbRo91Bh3kjUkmGhvsJTMouXL42rgXLMwRH5M40lKDgbxWvSN4YPFRuAduxrZGwrthqo1JclSAZfgqrYn0Xweutuj/jfBHbAwuV24F+idEL4aGL/vLshHKhVWwJeboYRfHqgS+Ktlx+IWNXSRqfn9PYfKLAkuTQJmOEvmjTWVYtUi+AhaPWU2MWrT9qzGsQwKoCd1yIMGBEk34KehsYdmfHLHrgL3BVzBjhd+KNZyJcppCXDk28h6ZFxD7VIPrk2ksJnheHytU+o3MfOUNtjtZKnToZKkQDiQegYZwOs3WXbKdPeFkfFYnX5gtkgKJrX0mLfzA52Day1ZQMAHbkkggmE7eCHfuFL9xwtIakiHAUWZMdJ0zlsLbGUWxiR7pVl6+pQ=
  file: ${PACKAGE}
  skip_cleanup: true
  on:
    tags: true
    repo: rwth-afu/UniPager
